services:
  db:
    image: postgis/postgis:16-3.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  api:
    build:
      context: ./backend
      dockerfile: docker/docker_files/Dockerfile
    platform: linux/arm64
    command: gunicorn django_api.wsgi:application -b 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
